# Generated by Django 2.1.5 on 2019-02-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['inst_id']},
        ),
        migrations.RemoveField(
            model_name='institution',
            name='inst_num',
        ),
        migrations.AddField(
            model_name='institution',
            name='inst_abbr',
            field=models.CharField(default='HC', max_length=10),
        ),
        migrations.AddField(
            model_name='institution',
            name='inst_id',
            field=models.CharField(default='CPTUCT', max_length=10),
        ),
        migrations.AddField(
            model_name='institution',
            name='inst_name',
            field=models.CharField(default='Herentals college', max_length=200),
        ),
    ]
